[package]
name = "aoc_import_magic"
version = "0.1.0"
authors = ["Fabian WÃ¼rfl <bafdyce@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
serde = "1"
serde_derive = "1"
serde_json = "1"